// <auto-generated />
using System;
using CorporateTMS_EFCore_Day4.Repository.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CorporateTMS_EFCore_Day4.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20260222204848_DefaultConstraint")]
    partial class DefaultConstraint
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CorporateTMS_EFCore_Day4.Repository.Model.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("varchar(70)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Location = "Ahmedabad",
                            Name = "IT"
                        },
                        new
                        {
                            Id = 2,
                            Location = "Mumbai",
                            Name = "HR"
                        },
                        new
                        {
                            Id = 3,
                            Location = "Chennai",
                            Name = "Sales"
                        },
                        new
                        {
                            Id = 4,
                            Location = "Delhi",
                            Name = "Marketing"
                        },
                        new
                        {
                            Id = 5,
                            Location = "Banglore",
                            Name = "Finance"
                        });
                });

            modelBuilder.Entity("CorporateTMS_EFCore_Day4.Repository.Model.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EmployeeType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasDiscriminator<string>("EmployeeType").HasValue("Emplpyee");

                    b.UseTphMappingStrategy();

                    b.HasData(
                        new
                        {
                            Id = 2,
                            DepartmentId = 2,
                            Email = "mann.b@company.com",
                            Name = "Mann"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 2,
                            Email = "krunal.k@company.com",
                            Name = "Krunal"
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 1,
                            Email = "niken.p@company.com",
                            Name = "Niken"
                        },
                        new
                        {
                            Id = 7,
                            DepartmentId = 3,
                            Email = "ashish.p@company.com",
                            Name = "Ashish"
                        },
                        new
                        {
                            Id = 8,
                            DepartmentId = 1,
                            Email = "raj.r@company.com",
                            Name = "Raj"
                        },
                        new
                        {
                            Id = 9,
                            DepartmentId = 3,
                            Email = "Meg.m@company.com",
                            Name = "Meg"
                        },
                        new
                        {
                            Id = 10,
                            DepartmentId = 5,
                            Email = "yash.p@company.com",
                            Name = "Yash"
                        });
                });

            modelBuilder.Entity("CorporateTMS_EFCore_Day4.Repository.Model.Enrollment", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("TrainerProgramId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EnrollDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PerformanceScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("EmployeeId", "TrainerProgramId");

                    b.HasIndex("TrainerProgramId");

                    b.ToTable("Enrollments", t =>
                        {
                            t.HasCheckConstraint("Enrollment_PerformanceScore", "[PerformanceScore]<=100");
                        });

                    b.HasData(
                        new
                        {
                            EmployeeId = 2,
                            TrainerProgramId = 1,
                            EnrollDate = new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PerformanceScore = 0
                        },
                        new
                        {
                            EmployeeId = 2,
                            TrainerProgramId = 2,
                            EnrollDate = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PerformanceScore = 0
                        },
                        new
                        {
                            EmployeeId = 4,
                            TrainerProgramId = 3,
                            EnrollDate = new DateTime(2026, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PerformanceScore = 0
                        },
                        new
                        {
                            EmployeeId = 4,
                            TrainerProgramId = 1,
                            EnrollDate = new DateTime(2026, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PerformanceScore = 0
                        },
                        new
                        {
                            EmployeeId = 3,
                            TrainerProgramId = 3,
                            EnrollDate = new DateTime(2026, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PerformanceScore = 0
                        },
                        new
                        {
                            EmployeeId = 3,
                            TrainerProgramId = 4,
                            EnrollDate = new DateTime(2026, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PerformanceScore = 0
                        },
                        new
                        {
                            EmployeeId = 6,
                            TrainerProgramId = 1,
                            EnrollDate = new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PerformanceScore = 0
                        },
                        new
                        {
                            EmployeeId = 8,
                            TrainerProgramId = 1,
                            EnrollDate = new DateTime(2026, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PerformanceScore = 0
                        });
                });

            modelBuilder.Entity("CorporateTMS_EFCore_Day4.Repository.Model.TrainingProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("TrainerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.HasIndex("TrainerId");

                    b.ToTable("TrainingPrograms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Duration = 2,
                            StartDate = new DateTime(2026, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "C# Fundamentals",
                            TrainerId = 3
                        },
                        new
                        {
                            Id = 2,
                            Duration = 1,
                            StartDate = new DateTime(2026, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Object Oriented Programming",
                            TrainerId = 1
                        },
                        new
                        {
                            Id = 3,
                            Duration = 2,
                            StartDate = new DateTime(2026, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Language Integrated Query",
                            TrainerId = 1
                        },
                        new
                        {
                            Id = 4,
                            Duration = 1,
                            StartDate = new DateTime(2026, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "EF Core",
                            TrainerId = 5
                        });
                });

            modelBuilder.Entity("CorporateTMS_EFCore_Day4.Repository.Model.Trainer", b =>
                {
                    b.HasBaseType("CorporateTMS_EFCore_Day4.Repository.Model.Employee");

                    b.Property<int>("ExpertiseLevel")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Trainer");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            Email = "aayush.p@company.com",
                            Name = "Aayush",
                            ExpertiseLevel = 5
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 1,
                            Email = "devam.s@company.com",
                            Name = "Devam",
                            ExpertiseLevel = 4
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 4,
                            Email = "het.p@company.com",
                            Name = "Het",
                            ExpertiseLevel = 4
                        });
                });

            modelBuilder.Entity("CorporateTMS_EFCore_Day4.Repository.Model.Employee", b =>
                {
                    b.HasOne("CorporateTMS_EFCore_Day4.Repository.Model.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("CorporateTMS_EFCore_Day4.Repository.Model.Enrollment", b =>
                {
                    b.HasOne("CorporateTMS_EFCore_Day4.Repository.Model.Employee", "Employee")
                        .WithMany("Enrollments")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CorporateTMS_EFCore_Day4.Repository.Model.TrainingProgram", "TrainerProgram")
                        .WithMany("Enrollments")
                        .HasForeignKey("TrainerProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("TrainerProgram");
                });

            modelBuilder.Entity("CorporateTMS_EFCore_Day4.Repository.Model.TrainingProgram", b =>
                {
                    b.HasOne("CorporateTMS_EFCore_Day4.Repository.Model.Trainer", "Trainer")
                        .WithMany("TrainingPrograms")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("CorporateTMS_EFCore_Day4.Repository.Model.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("CorporateTMS_EFCore_Day4.Repository.Model.Employee", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("CorporateTMS_EFCore_Day4.Repository.Model.TrainingProgram", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("CorporateTMS_EFCore_Day4.Repository.Model.Trainer", b =>
                {
                    b.Navigation("TrainingPrograms");
                });
#pragma warning restore 612, 618
        }
    }
}
