// <auto-generated />
using System;
using CorporateTMS_EFCore_Day4.Repository.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CorporateTMS_EFCore_Day4.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CorporateTMS_EFCore_Day4.Repository.Model.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("varchar(70)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("CorporateTMS_EFCore_Day4.Repository.Model.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EmployeeType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasDiscriminator<string>("EmployeeType").HasValue("Emplpyee");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("CorporateTMS_EFCore_Day4.Repository.Model.Enrollment", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("TrainerProgramId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EnrollDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PerformanceScore")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId", "TrainerProgramId");

                    b.HasIndex("TrainerProgramId");

                    b.ToTable("Enrollments", t =>
                        {
                            t.HasCheckConstraint("Enrollment_PerformanceScore", "[PerformanceScore]<=100");
                        });
                });

            modelBuilder.Entity("CorporateTMS_EFCore_Day4.Repository.Model.TrainingProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("TrainerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.HasIndex("TrainerId");

                    b.ToTable("TrainingPrograms");
                });

            modelBuilder.Entity("CorporateTMS_EFCore_Day4.Repository.Model.Trainer", b =>
                {
                    b.HasBaseType("CorporateTMS_EFCore_Day4.Repository.Model.Employee");

                    b.Property<int>("ExpertiseLevel")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Trainer");
                });

            modelBuilder.Entity("CorporateTMS_EFCore_Day4.Repository.Model.Employee", b =>
                {
                    b.HasOne("CorporateTMS_EFCore_Day4.Repository.Model.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("CorporateTMS_EFCore_Day4.Repository.Model.Enrollment", b =>
                {
                    b.HasOne("CorporateTMS_EFCore_Day4.Repository.Model.Employee", "Employee")
                        .WithMany("Enrollments")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CorporateTMS_EFCore_Day4.Repository.Model.TrainingProgram", "TrainerProgram")
                        .WithMany("Enrollments")
                        .HasForeignKey("TrainerProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("TrainerProgram");
                });

            modelBuilder.Entity("CorporateTMS_EFCore_Day4.Repository.Model.TrainingProgram", b =>
                {
                    b.HasOne("CorporateTMS_EFCore_Day4.Repository.Model.Trainer", "Trainer")
                        .WithMany("TrainingPrograms")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("CorporateTMS_EFCore_Day4.Repository.Model.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("CorporateTMS_EFCore_Day4.Repository.Model.Employee", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("CorporateTMS_EFCore_Day4.Repository.Model.TrainingProgram", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("CorporateTMS_EFCore_Day4.Repository.Model.Trainer", b =>
                {
                    b.Navigation("TrainingPrograms");
                });
#pragma warning restore 612, 618
        }
    }
}
